apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: sternshawn/expiration
          env:
            - name: NATS_URI
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              # Use the generated pod name as an env variable for easy lookup in k8s logs ✨
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
              # This service uses redis, so we'll need a bonus env var so it knows where to connect
            - name: REDIS_HOST
              value: expiration-redis-srv
# Unlike the other services, we aren't doing any direct network requests to this service,
# so no need for a clusterIP service like the others use to expose port 3000, etc 🔥
