apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # Port of this NodePort Service that internal requests should be directed to and will be directed to the targetPort
      targetPort: 4000 # The port of our express server that is listening for traffic
