projects:
  photoalbums:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: qpfp5oahhrd6bdurtpr2lt2cd4
      endpoints:
        prod: >-
          https://tfmto7zakveetkmdmznxsisb2m.appsync-api.us-west-2.amazonaws.com/graphql
